// ROLES
const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  HR: 'HR',
  ACCOUNTANT: 'ACCOUNTANT',
  STAFF: 'STAFF',
  CUSTOMER: 'CUSTOMER',
};

// ROLE HIERARCHY
const ROLE_HIERARCHY = {
  SUPER_ADMIN: 6,
  ADMIN: 5,
  MANAGER: 4,
  HR: 3,
  ACCOUNTANT: 3,
  STAFF: 2,
  CUSTOMER: 1,
};

// WHO CAN CREATE WHAT ROLE
const ROLE_CREATION_PERMISSIONS = {
  SUPER_ADMIN: ['SUPER_ADMIN', 'ADMIN', 'MANAGER', 'HR', 'ACCOUNTANT', 'STAFF', 'CUSTOMER'],
  ADMIN: ['MANAGER', 'HR', 'ACCOUNTANT', 'STAFF', 'CUSTOMER'],
  MANAGER: ['STAFF', 'CUSTOMER'],
  HR: ['STAFF'],
  ACCOUNTANT: [],
  STAFF: [],
  CUSTOMER: [],
};

// DEPARTMENTS
const DEPARTMENTS = {
  ADMINISTRATION: 'Administration',
  FINANCE: 'Finance',
  HUMAN_RESOURCES: 'Human Resources',
  FRONT_DESK: 'Front Desk',
  HOUSEKEEPING: 'Housekeeping',
  MAINTENANCE: 'Maintenance',
  SECURITY: 'Security',
};

// POSITIONS per department
const POSITIONS = {
  // Administration
  SUPER_ADMIN: 'Super Administrator',
  HOTEL_MANAGER: 'Hotel Manager',
  // Finance
  ACCOUNTANT: 'Accountant',
  FINANCE_OFFICER: 'Finance Officer',
  // HR
  HR_SPECIALIST: 'HR Specialist',
  HR_OFFICER: 'HR Officer',
  // Front Desk
  RECEPTIONIST: 'Receptionist',
  DESK_STAFF: 'Desk Staff',
  // Housekeeping
  CLEANING_STAFF: 'Cleaning Staff',
  HEAD_HOUSEKEEPER: 'Head Housekeeper',
  // Maintenance
  TECHNICIAN: 'Technician',
  MAINTENANCE_STAFF: 'Maintenance Staff',
};

// EMPLOYMENT STATUS
const EMPLOYMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  ON_LEAVE: 'ON_LEAVE',
  SUSPENDED: 'SUSPENDED',
  TERMINATED: 'TERMINATED',
};

// RESERVATION STATUS
const RESERVATION_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CHECKED_IN: 'CHECKED_IN',
  CHECKED_OUT: 'CHECKED_OUT',
  CANCELLED: 'CANCELLED',
  WAITLIST: 'WAITLIST',
};

// PAYMENT STATUS
const PAYMENT_STATUS = {
  UNPAID: 'UNPAID',
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

// PAYMENT INTENT STATUS
const PAYMENT_INTENT_STATUS = {
  INITIATED: 'INITIATED',
  AUTHORIZED: 'AUTHORIZED',
  CAPTURED: 'CAPTURED',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED',
};

// ROOM STATUS
const ROOM_STATUS = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  MAINTENANCE: 'MAINTENANCE',
  BLOCKED: 'BLOCKED',
};

// MAINTENANCE STATUS
const MAINTENANCE_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

// PAYROLL APPROVAL STATUS
const PAYROLL_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  PAID: 'PAID',
  REJECTED: 'REJECTED',
};

module.exports = {
  ROLES,
  ROLE_HIERARCHY,
  ROLE_CREATION_PERMISSIONS,
  DEPARTMENTS,
  POSITIONS,
  EMPLOYMENT_STATUS,
  RESERVATION_STATUS,
  PAYMENT_STATUS,
  PAYMENT_INTENT_STATUS,
  ROOM_STATUS,
  MAINTENANCE_STATUS,
  PAYROLL_STATUS,
};